version: '2'
services:
  web:
    container_name: 'aspnetcore-localization'
    image: 'aspnetcore-localization'
    build: ./LocalizationSample/
    ports: 
      - "5000:5000"
    depends_on:
      - 'postgres'
    environment:
      Npgsql__ConnectionString: User ID=postgres;Host=postgres;Database=POSTGRES_USER
      DB_HOSTNAME: postgres
      DB_PORT: 5432
    networks:
      - aspnetcoreapp-network
  postgres:
    container_name: 'postgres'
    image: postgres
    networks:
      - aspnetcoreapp-network
networks:
  aspnetcoreapp-network:
    driver: bridge
